### ISSUE TITLE
Defect / missing license metadata

### ISSUE THREAD

**Issue by PhorstenkampFuzzy** [tkem/cachetools#375]
Before reporting a bug, please make sure you have the latest `cachetools` version installed:
```
pip install --upgrade cachetools
```

**Describe the bug**
The current version of cachetools does not hava a valid license entry in the wheel:

https://pypi.org/project/cachetools/

Please fix this so it works again with authomatic audit tools!

Cachetools is a great library i love to use in my projects!

**Comment by tkem** [comment]
@PhorstenkampFuzzy: You're absolutely right, thanks for reporting!
This was caused by switching to _license expressions_ as per [PEP 639](https://peps.python.org/pep-0639/), but then using an outdated version of `twine` for uploading...
Should be fixed with cachetools version 6.2.4.

**Comment by PhorstenkampFuzzy** [comment]
Can confirm it works. Bit the license is still missing on pypi. Not sure why.
